package awal;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class jadwal extends javax.swing.JFrame {

    private void kosongkan(){
        txtKerja.setEditable(true);
        txtKerja.setText(null);
        txtID.setText(null);
        txtHari.setText(null);
        txtTime.setText(null);
    }
    
    private void tampilkan(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No ");
        model.addColumn("Pekerjaan");
        model.addColumn("id_jadwal");
        model.addColumn("hari");
        model.addColumn("time");
      
        try{
            int no=1; //buat nambahin kolom nomor
            String sql="SELECT *FROM jadwal";
            java.sql.Connection conn=(Connection)Awal.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet b=stm.executeQuery(sql);
            
            while(b.next()){
                model.addRow(new Object[]{no++, b.getString(1),b.getString(2)});
                
            }
          tabelJadwal.setModel(model);
        }catch (SQLException a){
            System.out.println("Error : "+a.getMessage());
        }
    }
    public jadwal() {
        initComponents();
        tampilkan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtKerja = new java.awt.TextField();
        txtID = new java.awt.TextField();
        txtTime = new java.awt.TextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelJadwal = new javax.swing.JTable();
        tbTambah = new javax.swing.JButton();
        tbSimpan = new javax.swing.JButton();
        tbHapus = new javax.swing.JButton();
        tbKeluar = new javax.swing.JButton();
        txtHari = new java.awt.TextField();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 153));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("JADWAL PEGAWAI");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 260, 30));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Pekerjaan");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 96, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("id_jadwal");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 156, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("hari");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 120, -1));

        jLabel5.setBackground(new java.awt.Color(255, 153, 0));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("time");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 69, -1));

        txtKerja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKerjaActionPerformed(evt);
            }
        });
        getContentPane().add(txtKerja, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 119, -1));

        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        getContentPane().add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 157, 127, -1));

        txtTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimeActionPerformed(evt);
            }
        });
        getContentPane().add(txtTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 127, -1));

        tabelJadwal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nomor", "Pekerjaan", "id_jadwal", "Hari", "Time"
            }
        ));
        tabelJadwal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelJadwalMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelJadwal);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 610, 100));

        tbTambah.setForeground(new java.awt.Color(255, 0, 0));
        tbTambah.setText("Tambah Data");
        tbTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbTambahActionPerformed(evt);
            }
        });
        getContentPane().add(tbTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(513, 103, -1, -1));

        tbSimpan.setForeground(new java.awt.Color(255, 0, 0));
        tbSimpan.setText("Simpan");
        tbSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(tbSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(513, 157, -1, -1));

        tbHapus.setForeground(new java.awt.Color(255, 0, 0));
        tbHapus.setText("Hapus");
        tbHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbHapusActionPerformed(evt);
            }
        });
        getContentPane().add(tbHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(513, 208, -1, -1));

        tbKeluar.setForeground(new java.awt.Color(204, 0, 0));
        tbKeluar.setText("Keluar");
        tbKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(tbKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(513, 263, -1, -1));

        txtHari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHariActionPerformed(evt);
            }
        });
        getContentPane().add(txtHari, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 130, -1));

        jPanel4.setBackground(new java.awt.Color(255, 153, 153));
        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 520));

        jPanel2.setBackground(new java.awt.Color(255, 0, 102));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 210, 70));

        jPanel5.setBackground(new java.awt.Color(255, 0, 102));
        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 230, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtKerjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKerjaActionPerformed

        kosongkan();
    }//GEN-LAST:event_txtKerjaActionPerformed

    private void txtTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimeActionPerformed
   
        kosongkan();
    }//GEN-LAST:event_txtTimeActionPerformed

    private void tbTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbTambahActionPerformed
  
        kosongkan();
        txtKerja.setFocusable(true);
    }//GEN-LAST:event_tbTambahActionPerformed

    private void tbKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbKeluarActionPerformed
  
        System.exit(0);
    }//GEN-LAST:event_tbKeluarActionPerformed

    private void tbSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbSimpanActionPerformed
        
            try{
            String sql;
            sql = "insert into jadwal values('"+txtKerja.getText()+"','"+txtID.getText()+"','"+txtHari.getText()+"','"+txtTime.getText()+"')";
            java.sql.Connection conn=(Connection)Awal.configDB();
            java.sql.PreparedStatement pstm=conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null,"Data Berhasil Ditambahkan");
            tampilkan();
            kosongkan();
        }
           catch(HeadlessException | SQLException a){
            JOptionPane.showMessageDialog(this,a.getMessage());
        }
    }//GEN-LAST:event_tbSimpanActionPerformed

    private void tbHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbHapusActionPerformed
       
        try{
            String sql="delete from jadwal where Pekerjaan='"+txtKerja.getText()+"'";
            java.sql.Connection conn=(Connection)Awal.configDB();
            java.sql.PreparedStatement pstm=conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null,"Berhasil Hapus data");
        }catch(HeadlessException | SQLException a){
            JOptionPane.showMessageDialog(this,a.getMessage());
        }
        tampilkan();
        kosongkan();
    }//GEN-LAST:event_tbHapusActionPerformed

    private void tabelJadwalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelJadwalMouseClicked
      
        int baris = tabelJadwal.rowAtPoint(evt.getPoint());
        
        String Pekerjaan = tabelJadwal.getValueAt(baris, 1).toString();
        txtKerja.setText(Pekerjaan);
        
        String id_jadwal = tabelJadwal.getValueAt(baris, 2).toString();
        txtID.setText(id_jadwal);
       
        String hari = tabelJadwal.getValueAt(baris, 3).toString();
        txtHari.setText(hari);
        
        String time= tabelJadwal.getValueAt(baris, 4).toString();
        txtTime.setText(time);
    }//GEN-LAST:event_tabelJadwalMouseClicked

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        
        kosongkan();
    }//GEN-LAST:event_txtIDActionPerformed

    private void txtHariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHariActionPerformed

        kosongkan();
    }//GEN-LAST:event_txtHariActionPerformed

  
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(() -> {
            new jadwal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelJadwal;
    private javax.swing.JButton tbHapus;
    private javax.swing.JButton tbKeluar;
    private javax.swing.JButton tbSimpan;
    private javax.swing.JButton tbTambah;
    private java.awt.TextField txtHari;
    private java.awt.TextField txtID;
    private java.awt.TextField txtKerja;
    private java.awt.TextField txtTime;
    // End of variables declaration//GEN-END:variables
}
