package awal;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class jasa extends javax.swing.JFrame {

     private void kosongkan(){
        txtJenis.setEditable(true);
        txtJenis.setText(null);
        txtAlat.setText(null);
        txtJumlah.setText(null);
        txtID.setText(null);
    }
    private void tampilkan(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No ");
        model.addColumn("Jenis Jasa");
        model.addColumn("Peralatan");
        model.addColumn("Jumlah Alat");
        model.addColumn("ID Pegawai");
        try{
            int no=1; //buat nambahin kolom nomor
            String sql="SELECT *FROM jasa"; //memanggil nama file kita
            java.sql.Connection conn=(Connection)Awal.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet b=stm.executeQuery(sql);
            
            while(b.next()){
                model.addRow(new Object[]{no++, b.getString(1),b.getString(2),b.getString(3),b.getString(4)});
                
            }
          tabelJasa.setModel(model);
        }catch (SQLException a){
            System.out.println("Error : "+a.getMessage());
        }
    }

    public jasa() {
        initComponents();
        tampilkan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtAlat = new javax.swing.JTextField();
        txtJumlah = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        txtJenis = new javax.swing.JTextField();
        txtSimpan = new javax.swing.JButton();
        txtHapus = new javax.swing.JButton();
        txtKeluar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelJasa = new javax.swing.JTable();
        txtTambah = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Jenis Jasa");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 89, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Peralatan");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Jumlah Alat");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 203, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("ID Pegawai");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 255, -1, -1));

        txtAlat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlatActionPerformed(evt);
            }
        });
        getContentPane().add(txtAlat, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 139, 127, -1));

        txtJumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJumlahActionPerformed(evt);
            }
        });
        getContentPane().add(txtJumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 202, 127, -1));

        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        getContentPane().add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 254, 127, -1));

        txtJenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJenisActionPerformed(evt);
            }
        });
        getContentPane().add(txtJenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 86, 127, -1));

        txtSimpan.setForeground(new java.awt.Color(255, 0, 51));
        txtSimpan.setText("Simpan");
        txtSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(txtSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 100, -1));

        txtHapus.setForeground(new java.awt.Color(255, 0, 51));
        txtHapus.setText("Hapus");
        txtHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHapusActionPerformed(evt);
            }
        });
        getContentPane().add(txtHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, 100, -1));

        txtKeluar.setForeground(new java.awt.Color(255, 0, 51));
        txtKeluar.setText("Keluar");
        txtKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(txtKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(513, 322, 100, -1));

        tabelJasa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nomor", "Jenis Jasa", "Peralatan", "Jumlah Alat", "ID Pegawai"
            }
        ));
        tabelJasa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelJasaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelJasa);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 384, 593, 100));

        txtTambah.setForeground(new java.awt.Color(255, 0, 51));
        txtTambah.setText("Tambah Data");
        txtTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTambahActionPerformed(evt);
            }
        });
        getContentPane().add(txtTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 110, -1));

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TABEL JASA");
        jPanel1.add(jLabel1);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlahActionPerformed
       
        kosongkan();
    }//GEN-LAST:event_txtJumlahActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
     
        kosongkan();
    }//GEN-LAST:event_txtIDActionPerformed

    private void txtAlatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlatActionPerformed

        kosongkan();
    }//GEN-LAST:event_txtAlatActionPerformed

    private void txtJenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJenisActionPerformed
      
        kosongkan();
    }//GEN-LAST:event_txtJenisActionPerformed

    private void txtSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSimpanActionPerformed
        
            try{
            String sql;
            sql = "insert into jasa values('"+txtJenis.getText()+"','"+txtAlat.getText()+"','"+txtJumlah.getText()+"','"+txtID.getText()+"')";
            java.sql.Connection conn=(Connection)Awal.configDB();
            java.sql.PreparedStatement pstm=conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null,"Data Berhasil Ditambahkan");
            tampilkan();
            kosongkan();
        }
           catch(HeadlessException | SQLException a){
            JOptionPane.showMessageDialog(this,a.getMessage());
        }
    }//GEN-LAST:event_txtSimpanActionPerformed

    private void txtHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHapusActionPerformed
       
        try{
            String sql="delete from jasa where jenis_jasa='"+txtJenis.getText()+"'";
            java.sql.Connection conn=(Connection)Awal.configDB();
            java.sql.PreparedStatement pstm=conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null,"Berhasil Hapus data");
        }catch(HeadlessException | SQLException a){
            JOptionPane.showMessageDialog(this,a.getMessage());
        }
        tampilkan();
        kosongkan();
    }//GEN-LAST:event_txtHapusActionPerformed

    private void txtKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKeluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_txtKeluarActionPerformed

    private void tabelJasaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelJasaMouseClicked
       
        int baris = tabelJasa.rowAtPoint(evt.getPoint());
        
        String jenis_jasa = tabelJasa.getValueAt(baris, 1).toString();
        txtJenis.setText(jenis_jasa);
        
        String peralatan = tabelJasa.getValueAt(baris, 2).toString();
        txtAlat.setText(peralatan);
       
        String jumlah_alat = tabelJasa.getValueAt(baris, 3).toString();
        txtJumlah.setText(jumlah_alat);
        String id_pegawai = tabelJasa.getValueAt(baris, 4).toString();
        txtID.setText(id_pegawai);
    }//GEN-LAST:event_tabelJasaMouseClicked

    private void txtTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTambahActionPerformed
    
        kosongkan();
        txtJenis.setFocusable(true);
    }//GEN-LAST:event_txtTambahActionPerformed

  
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(() -> {
            new jasa().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelJasa;
    private javax.swing.JTextField txtAlat;
    private javax.swing.JButton txtHapus;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtJenis;
    private javax.swing.JTextField txtJumlah;
    private javax.swing.JButton txtKeluar;
    private javax.swing.JButton txtSimpan;
    private javax.swing.JButton txtTambah;
    // End of variables declaration//GEN-END:variables
}
