/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package awal;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author ASUS
 */
public class keluhann extends javax.swing.JFrame {
 private void kosongkan(){
        txtTanggal.setEditable(true);
        txtTanggal.setText(null);
        txtKeluhan.setText(null);
        txtAlasan.setText(null);
        
    }
    private void tampilkan(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No ");
        model.addColumn("Tanggal ");
        model.addColumn("keluhan");
        model.addColumn("alasan");
      
        try{
            int no=1; //buat nambahin kolom nomor
            String sql="SELECT *FROM keluhan";
            java.sql.Connection conn=(Connection)Awal.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet b=stm.executeQuery(sql);
            
            while(b.next()){
                model.addRow(new Object[]{no++, b.getString(1),b.getString(2),b.getString(3)});
                
            }
          tabelKeluhann.setModel(model);
        }catch (SQLException a){
            System.out.println("Error : "+a.getMessage());
        }
    }

    /**
     * Creates new form keluhann
     */
    public keluhann() {
        initComponents();
        tampilkan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTanggal = new java.awt.TextField();
        txtKeluhan = new java.awt.TextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelKeluhann = new javax.swing.JTable();
        tbSimpan = new javax.swing.JButton();
        tbEdit = new javax.swing.JButton();
        tbHapus = new javax.swing.JButton();
        tbBatal = new javax.swing.JButton();
        tbKeluar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtAlasan = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Tanggal");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 107, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Keluhan");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 210, -1, -1));
        getContentPane().add(txtTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 107, 157, -1));

        txtKeluhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKeluhanActionPerformed(evt);
            }
        });
        getContentPane().add(txtKeluhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 210, 160, 30));

        tabelKeluhann.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tabelKeluhann.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nomor", "Tanggal", "Keluhan", "alasan"
            }
        ));
        tabelKeluhann.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelKeluhannMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelKeluhann);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, 450, 98));

        tbSimpan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tbSimpan.setForeground(new java.awt.Color(204, 0, 0));
        tbSimpan.setText("Simpan");
        tbSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(tbSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, 100, -1));

        tbEdit.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tbEdit.setForeground(new java.awt.Color(204, 0, 0));
        tbEdit.setText("Edit");
        tbEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbEditActionPerformed(evt);
            }
        });
        getContentPane().add(tbEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 280, 100, -1));

        tbHapus.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tbHapus.setForeground(new java.awt.Color(204, 0, 0));
        tbHapus.setText("Hapus");
        tbHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbHapusActionPerformed(evt);
            }
        });
        getContentPane().add(tbHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 220, 100, -1));

        tbBatal.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tbBatal.setForeground(new java.awt.Color(204, 0, 0));
        tbBatal.setText("Batal");
        tbBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbBatalActionPerformed(evt);
            }
        });
        getContentPane().add(tbBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 280, 100, -1));

        tbKeluar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tbKeluar.setForeground(new java.awt.Color(204, 0, 0));
        tbKeluar.setText("Keluar");
        tbKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(tbKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 240, 100, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Alasan");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 60, 20));

        txtAlasan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlasanActionPerformed(evt);
            }
        });
        getContentPane().add(txtAlasan, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 180, 160));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FORM KELUHAN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 102, 102));
        jPanel2.setForeground(new java.awt.Color(255, 255, 0));
        jPanel2.add(jLayeredPane1);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbHapusActionPerformed
        // TODO add your handling code here:
            try{
            String sql="delete from keluhan where tanggal='"+txtTanggal.getText()+"'";
            java.sql.Connection conn=(Connection)Awal.configDB();
            java.sql.PreparedStatement pstm=conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null,"Berhasil Hapus data");
        }
             catch(HeadlessException | SQLException a){
            JOptionPane.showMessageDialog(this,a.getMessage());
        }
        tampilkan();
        kosongkan();
    }//GEN-LAST:event_tbHapusActionPerformed

    private void tbSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbSimpanActionPerformed
        // TODO add your handling code here:
            try{
            String sql;
            sql = "insert into keluhan values('"+txtTanggal.getText()+"','"+txtKeluhan.getText()+"','"+txtAlasan.getText()+"')";
            java.sql.Connection conn=(Connection)Awal.configDB();
            java.sql.PreparedStatement pstm=conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null,"Data Berhasil Ditambahkan");
            tampilkan();
            kosongkan();
        }
           catch(HeadlessException | SQLException a){
            JOptionPane.showMessageDialog(this,a.getMessage());
        }
    }//GEN-LAST:event_tbSimpanActionPerformed

    private void tbEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbEditActionPerformed
        // TODO add your handling code here:
        try{
            String sql;
            sql = "update keluhan set tanggal='"+txtTanggal.getText()+"',Keluhan='"+txtKeluhan.getText()+"',Alasan='"+txtAlasan.getText()+"' where tanggal='"+txtTanggal.getText()+"'";
            java.sql.Connection conn=(Connection)Awal.configDB();
            java.sql.PreparedStatement pstm=conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null,"Berhasil Edit data");
        }
        catch(HeadlessException | SQLException a){
            JOptionPane.showMessageDialog(this,a.getMessage());
        }
        tampilkan();
        kosongkan();
    }//GEN-LAST:event_tbEditActionPerformed

    private void tbBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbBatalActionPerformed
        // TODO add your handling code here:
        kosongkan();
    }//GEN-LAST:event_tbBatalActionPerformed

    private void tbKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbKeluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_tbKeluarActionPerformed

    private void tabelKeluhannMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelKeluhannMouseClicked
        // TODO add your handling code here:
        int baris = tabelKeluhann.rowAtPoint(evt.getPoint());

        String tanggal = tabelKeluhann.getValueAt(baris, 1).toString();
        txtTanggal.setText(tanggal);

        String keluhan = tabelKeluhann.getValueAt(baris, 2).toString();
        txtKeluhan.setText(keluhan);
        
        String alasan = tabelKeluhann.getValueAt(baris, 2).toString();
        txtAlasan.setText(alasan);    
        
    }//GEN-LAST:event_tabelKeluhannMouseClicked

    private void txtAlasanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlasanActionPerformed
        // TODO add your handling code here:
        kosongkan();
    }//GEN-LAST:event_txtAlasanActionPerformed

    private void txtKeluhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKeluhanActionPerformed
        // TODO add your handling code here:
        kosongkan();
    }//GEN-LAST:event_txtKeluhanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(keluhann.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(keluhann.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(keluhann.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(keluhann.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new keluhann().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelKeluhann;
    private javax.swing.JButton tbBatal;
    private javax.swing.JButton tbEdit;
    private javax.swing.JButton tbHapus;
    private javax.swing.JButton tbKeluar;
    private javax.swing.JButton tbSimpan;
    private javax.swing.JTextField txtAlasan;
    private java.awt.TextField txtKeluhan;
    private java.awt.TextField txtTanggal;
    // End of variables declaration//GEN-END:variables
}
